# Generated by Django 2.2.5 on 2022-01-13 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0004_auto_20220114_0225"),
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lists",
            new_name="List",
        ),
    ]
